backend:
  name: github
  repo: c130guy/Larrysgunroom
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "featured"
    label: "Featured Firearms"
    folder: "content/featured"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Available", "SOLD", "ON HOLD"] }
      - { label: "Image", name: "image", widget: "image" }
